theme: jekyll-theme-architect

lsi: false
safe: true
source: https://github.com/wakatsuki-moe/Tutorial/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 
